services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/server
    environment:
      - NODE_ENV=development
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/client
    environment:
      - NODE_ENV=development
    restart: always

  db:
    image: postgres:latest
    container_name: vue-saas-postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_LOAD_DEFINITIONS: /etc/rabbitmq/definitions.json
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - ./rabbit-mq/definitions.json:/etc/rabbitmq/definitions.json:ro

volumes:
  postgres_data:
  rabbitmq-data:
